# Generated by Django 4.2.16 on 2025-11-04 18:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('building', models.CharField(blank=True, max_length=200)),
                ('zone', models.CharField(blank=True, max_length=200)),
                ('mqtt_broker', models.CharField(max_length=255)),
                ('mqtt_port', models.IntegerField(default=1883)),
                ('mqtt_topic', models.CharField(max_length=255)),
                ('mqtt_username', models.CharField(blank=True, max_length=100)),
                ('mqtt_password', models.CharField(blank=True, max_length=100)),
                ('voltage_min', models.IntegerField(default=11000)),
                ('voltage_max', models.IntegerField(default=13500)),
                ('temperature_min', models.IntegerField(default=0)),
                ('temperature_max', models.IntegerField(default=450)),
                ('soc_min', models.IntegerField(default=20)),
                ('soh_min', models.IntegerField(default=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['station_id'],
            },
        ),
        migrations.CreateModel(
            name='BatteryStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('battery_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('avg_voltage', models.FloatField()),
                ('min_voltage', models.IntegerField()),
                ('max_voltage', models.IntegerField()),
                ('avg_temperature', models.FloatField()),
                ('min_temperature', models.IntegerField()),
                ('max_temperature', models.IntegerField()),
                ('avg_soc', models.FloatField()),
                ('min_soc', models.IntegerField()),
                ('max_soc', models.IntegerField()),
                ('avg_soh', models.FloatField()),
                ('min_soh', models.IntegerField()),
                ('max_soh', models.IntegerField()),
                ('alert_count', models.IntegerField(default=0)),
                ('critical_alerts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='batteries.batterystation')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('station', 'battery_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BatteryReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('battery_id', models.CharField(max_length=50)),
                ('voltage', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('soc', models.IntegerField()),
                ('soh', models.IntegerField()),
                ('imp', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='batteries.batterystation')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['station', '-timestamp'], name='batteries_b_station_8e8ea8_idx'), models.Index(fields=['station', 'battery_id', '-timestamp'], name='batteries_b_station_87003e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatteryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('battery_id', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('message', models.TextField()),
                ('voltage', models.IntegerField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('soc', models.IntegerField(blank=True, null=True)),
                ('soh', models.IntegerField(blank=True, null=True)),
                ('imp', models.IntegerField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('alert_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='batteries.batterystation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['station', '-created_at'], name='batteries_b_station_4bac61_idx'), models.Index(fields=['severity', '-created_at'], name='batteries_b_severit_5bb5ba_idx')],
            },
        ),
    ]
