# Generated by Django 4.2.16 on 2026-02-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterystation',
            name='imp_max',
            field=models.IntegerField(default=160),
        ),
    ]
