# Generated by Django 4.2.16 on 2026-02-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0002_batterystation_imp_max'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batteryreading',
            unique_together={('station', 'battery_id', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='batteryalert',
            index=models.Index(fields=['station', 'battery_id', 'alert_time'], name='batteries_b_station_f24975_idx'),
        ),
    ]
