# Generated by Django 4.2.16 on 2026-04-05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0003_alter_batteryreading_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationNotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_email', models.EmailField(blank=True, max_length=254)),
                ('csv_email', models.EmailField(blank=True, max_length=254)),
                ('alert_phone', models.CharField(blank=True, max_length=32)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('csv_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='batteries.batterystation')),
            ],
            options={
                'ordering': ['station__station_id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('csv', 'CSV')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='batteries.batteryalert')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='batteries.batterystation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['station', '-created_at'], name='batteries_n_station_0d4d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['channel', '-created_at'], name='batteries_n_channel_7e4db0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['status', '-created_at'], name='batteries_n_status_7dfd0f_idx'),
        ),
    ]
