# Generated by Django 4.2.16 on 2026-04-05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0004_notification_delivery_log_station_notification_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(default='global', max_length=32, unique=True)),
                ('alert_email', models.EmailField(blank=True, max_length=254)),
                ('csv_email', models.EmailField(blank=True, max_length=254)),
                ('alert_phone', models.CharField(blank=True, max_length=32)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('csv_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scope'],
            },
        ),
    ]