# Generated by Django 4.2.16 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0005_global_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnotificationsettings',
            name='last_all_digest_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalnotificationsettings',
            name='last_all_digest_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='globalnotificationsettings',
            name='last_hourly_digest_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalnotificationsettings',
            name='last_hourly_digest_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]