"use client"

import { useMemo, useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Search, Settings } from "lucide-react"
import { ActivityNotification } from "@/components/activity-notification"
import { BatteryDetailsModal } from "@/components/battery-details-modal"
import { useBatteryAlerts, useBatteryHistory, acknowledgeAlert } from "@/hooks/use-batteries"
import { ThresholdSettings } from "@/components/threshold-settings"

type BatteryData = {
  stationId: string
  batteryId: string
  voltage: number
  temperature: number
  soc: number
  soh: number
  imp: number
  timestamp: string
}

export default function IntelligencePage() {
  const [searchTerm, setSearchTerm] = useState("")
  const [severity, setSeverity] = useState<"all" | "critical" | "warning" | "info">("all")
  const [selected, setSelected] = useState<{ stationId: string; batteryId: string } | null>(null)
  const [isDetailsOpen, setIsDetailsOpen] = useState(false)
  const [isSettingsOpen, setIsSettingsOpen] = useState(false)

  // Alerts feed across all stations (from backend — includes threshold-based alerts generated by MQTT handler)
  const { alerts, mutate: mutateAlerts } = useBatteryAlerts(undefined, severity === "all" ? undefined : severity)

  // Pull recent history when a selection exists
  const { history } = useBatteryHistory(selected?.stationId || "", selected?.batteryId || "", 50)

  const current: BatteryData | null = useMemo(() => {
    if (!selected) return null
    if (history && history.length > 0) return history[history.length - 1]
    return null
  }, [history, selected])

  const filtered = alerts.filter((a: any) => {
    // Apply severity filter for client-side threshold alerts
    if (severity !== "all" && a.severity !== severity) return false
    // Apply search filter
    const q = searchTerm.trim().toLowerCase()
    if (!q) return true
    return (
      a.stationId.toLowerCase().includes(q) ||
      a.batteryId.toLowerCase().includes(q) ||
      a.message.toLowerCase().includes(q)
    )
  })

  const handleAcknowledge = async (alertId: string) => {
    try {
      await acknowledgeAlert(alertId)
      mutateAlerts()
    } catch (e) {
      console.error("Failed to acknowledge:", e)
    }
  }

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground tracking-wider">ACTIVITY CENTER</h1>
          <p className="text-sm text-muted-foreground">Live battery activity and alerts, tuned and actionable</p>
        </div>
        <div className="flex gap-2">
          <Button
            variant={severity === "all" ? "default" : "outline"}
            className={severity === "all" ? "bg-orange-600 hover:bg-orange-700 text-white" : "border-border"}
            onClick={() => setSeverity("all")}
          >
            All
          </Button>
          <Button
            variant={severity === "critical" ? "default" : "outline"}
            className={severity === "critical" ? "bg-red-600 hover:bg-red-700 text-white" : "border-border"}
            onClick={() => setSeverity("critical")}
          >
            Critical
          </Button>
          <Button
            variant={severity === "warning" ? "default" : "outline"}
            className={severity === "warning" ? "bg-orange-600 hover:bg-orange-700 text-white" : "border-border"}
            onClick={() => setSeverity("warning")}
          >
            Warning
          </Button>
          <Button
            variant={severity === "info" ? "default" : "outline"}
            className={severity === "info" ? "bg-foreground hover:bg-foreground/90 text-background" : "border-border"}
            onClick={() => setSeverity("info")}
          >
            Info
          </Button>
          <Button
            variant="outline"
            className="border-border text-muted-foreground hover:bg-muted hover:text-foreground"
            onClick={() => setIsSettingsOpen(true)}
            title="Threshold settings"
          >
            <Settings className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {/* Search */}
      <Card className="bg-card border-border">
        <CardContent className="p-4">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="Search station, battery, or message..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10 bg-background border-border text-foreground placeholder:text-muted-foreground"
            />
          </div>
        </CardContent>
      </Card>

      {/* Main grid: Alerts feed and details panel */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Alerts Feed */}
        <Card className="lg:col-span-7 bg-card border-border">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground tracking-wider">ACTIVITY NOTIFICATIONS</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {filtered.map((a: any, idx: number) => (
                <ActivityNotification
                  key={a.id || `${a.stationId}-${a.batteryId}-${idx}`}
                  id={a.id || `${a.stationId}-${a.batteryId}-${idx}`}
                  timestamp={new Date(a.timestamp).toLocaleTimeString()}
                  type={a.severity as any}
                  title={`${a.severity.toUpperCase()} — STN ${a.stationId} / ${a.batteryId}`}
                  description={a.message}
                  station={a.stationId}
                  battery={a.batteryId}
                  acknowledged={a.acknowledged}
                  onClick={() => {
                    setSelected({ stationId: a.stationId, batteryId: a.batteryId })
                    setIsDetailsOpen(true)
                  }}
                  onAcknowledge={
                    a.id && !a.acknowledged
                      ? () => handleAcknowledge(a.id)
                      : undefined
                  }
                />
              ))}
              {filtered.length === 0 && (
                <div className="text-xs text-muted-foreground">No alerts match your filters.</div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Details Panel */}
        <Card className="lg:col-span-5 bg-card border-border">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-bold text-muted-foreground tracking-wider">ALERT DETAILS</CardTitle>
          </CardHeader>
          <CardContent>
            {!selected && (
              <div className="text-xs text-muted-foreground">Select an alert to view details.</div>
            )}

            {selected && (
              <div className="space-y-3">
                <div className="text-xs text-muted-foreground font-mono">
                  STN {selected.stationId} / {selected.batteryId}
                </div>

                {/* System-style quick metrics */}
                <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                  <div className="bg-muted p-2 rounded">
                    <div className="text-[10px] text-muted-foreground tracking-wider">VOLTAGE</div>
                    <div className="text-lg font-bold text-foreground font-mono">
                      {current ? (current.voltage / 1000).toFixed(2) + "V" : "—"}
                    </div>
                  </div>
                  <div className="bg-muted p-2 rounded">
                    <div className="text-[10px] text-muted-foreground tracking-wider">TEMPERATURE</div>
                    <div className="text-lg font-bold text-foreground font-mono">
                      {current ? (current.temperature / 10).toFixed(1) + "°C" : "—"}
                    </div>
                  </div>
                  <div className="bg-muted p-2 rounded">
                    <div className="text-[10px] text-muted-foreground tracking-wider">SOC</div>
                    <div className="text-lg font-bold text-foreground font-mono">{current ? current.soc + "%" : "—"}</div>
                  </div>
                  <div className="bg-muted p-2 rounded">
                    <div className="text-[10px] text-muted-foreground tracking-wider">HEALTH</div>
                    <div className="text-lg font-bold text-foreground font-mono">{current ? current.soh + "%" : "—"}</div>
                  </div>
                  <div className="bg-muted p-2 rounded">
                    <div className="text-[10px] text-muted-foreground tracking-wider">IMPEDANCE</div>
                    <div className="text-lg font-bold text-foreground font-mono">
                      {current ? (current.imp / 1000).toFixed(2) + "Ω" : "—"}
                    </div>
                  </div>
                </div>

                <Button
                  onClick={() => setIsDetailsOpen(true)}
                  className="w-full bg-orange-600 hover:bg-orange-700 text-white text-xs"
                >
                  VIEW FULL ANALYTICS
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Full analytics modal mirrors the notification click behavior */}
      <BatteryDetailsModal
        isOpen={isDetailsOpen && !!selected}
        onClose={() => setIsDetailsOpen(false)}
        batteryData={current}
        historyData={history}
      />

      <ThresholdSettings open={isSettingsOpen} onOpenChange={setIsSettingsOpen} />
    </div>
  )
}
